# Generated by Django 4.0.4 on 2022-05-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='id',
        ),
        migrations.AlterField(
            model_name='bid',
            name='Order',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
