# Generated by Django 4.0.4 on 2022-05-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_bid_id_alter_bid_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='Name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='bid',
            name='lowest_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
