<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-05-07 01:32
=======
# Generated by Django 4.0.4 on 2022-05-07 18:56
>>>>>>> 816e6055347c9fb134142b6a81de64816a271339

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_funds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='salary',
            field=models.BigIntegerField(default=0),
        ),
    ]
