# Generated by Django 4.0.4 on 2022-05-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0004_customer_is_vip_customer_warnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='salary',
            field=models.BigIntegerField(default=0),
        ),
    ]
