# Generated by Django 4.0.4 on 2022-05-16 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0005_alter_chef_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAssociate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('salary', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('chef', 'Chef'), ('delivery', 'Delivery'), ('manager', 'Manager'), ('sales', 'Sales Associate')], max_length=30),
        ),
    ]
