# Generated by Django 4.0.4 on 2022-05-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0006_salesassociate_user_is_sales_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverer',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='manager',
            name='salary',
            field=models.BigIntegerField(default=0),
        ),
    ]
