# Generated by Django 4.0.4 on 2022-05-07 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_posts',
            name='reviewed_by_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='forum_posts',
            name='post_user',
        ),
        migrations.AddField(
            model_name='forum_posts',
            name='post_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
