# Generated by Django 4.0.4 on 2022-05-10 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0004_alter_forum_posts_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum_posts',
            name='reviewed_by_manager',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=10)),
                ('is_complaint', models.BooleanField(blank=True, default=False)),
                ('subject', models.CharField(max_length=40)),
                ('reviewed_by_manager', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
