# Generated by Django 4.0.4 on 2022-05-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_review_complainee_alter_review_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
