# Generated by Django 4.0.4 on 2022-05-17 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0008_ordermodel_is_paid'),
        ('forums', '0014_alter_review_complainee'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order_assigned',
            field=models.OneToOneField(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='order_system.ordermodel'),
            preserve_default=False,
        ),
    ]
