# Generated by Django 4.0.4 on 2022-05-17 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0008_ordermodel_is_paid'),
        ('forums', '0016_alter_review_order_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_system.ordermodel'),
        ),
    ]
