# Generated by Django 4.0.4 on 2022-05-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='description',
            field=models.CharField(default='No description given', max_length=300),
        ),
    ]
