# Generated by Django 4.0.4 on 2022-05-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_fooditem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
