# Generated by Django 4.0.4 on 2022-05-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_fooditem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='quantity_ordered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
