# Generated by Django 4.0.4 on 2022-05-11 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0006_fooditem_quantity_ordered_fooditem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='chef_name',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
