# Generated by Django 4.0.4 on 2022-05-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_fooditem_quantity_ordered_fooditem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
