# Generated by Django 4.0.4 on 2022-05-12 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_fooditem_exclusive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='exclusive',
            new_name='vip_exclusive',
        ),
    ]
