# Generated by Django 4.0.4 on 2022-05-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_fooditem_chef_name'),
        ('menu', '0008_rename_exclusive_fooditem_vip_exclusive'),
    ]

    operations = [
    ]
