# Generated by Django 4.0.4 on 2022-05-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_merge_20220512_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='rating',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
