# Generated by Django 4.0.4 on 2022-05-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_fooditem_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
