# Generated by Django 4.0.4 on 2022-05-10 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_system', '0002_ordermodel_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='deliver_person',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='is_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
