# Generated by Django 4.0.4 on 2022-05-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0004_alter_ordermodel_deliver_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='deliver_person',
        ),
    ]
