# Generated by Django 4.0.4 on 2022-05-10 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_system', '0005_remove_ordermodel_deliver_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='deliver_person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
